# Semana 11 — AED com dados simples: desempenho de estudantes

Este notebook trabalha os conteúdos das aulas de **Análise Exploratória de Dados (AED)** usando uma NOVA base 

## Objetivo da aula

O foco aqui não é apenas calcular com Python. O foco é **interpretar o que os resultados querem dizer**.

## 1. Preparação do ambiente

In [1]:
# Bibliotecas principais
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Configuração para exibir mais colunas
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

## 2. Carregando os dados

Coloque o arquivo `StudentsPerformance.csv` na mesma pasta deste notebook.

In [2]:
# Leitura do CSV baixado manualmente do Kaggle
arquivo = "StudentsPerformance.csv"
df = pd.read_csv(arquivo)

# Visualizar as primeiras linhas
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

## 3. Renomeando colunas para português

Para facilitar a aula, vamos traduzir os nomes das colunas.

In [3]:
df = df.rename(columns={
    'gender': 'genero',
    'race/ethnicity': 'grupo_etnico',
    'parental level of education': 'escolaridade_pais',
    'lunch': 'tipo_almoco',
    'test preparation course': 'curso_preparatorio',
    'math score': 'nota_matematica',
    'reading score': 'nota_leitura',
    'writing score': 'nota_escrita'
})

df.head()

,genero,grupo_etnico,escolaridade_pais,tipo_almoco,curso_preparatorio,nota_matematica,nota_leitura,nota_escrita
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Nível fácil — conhecer os dados

Nesta primeira parte, o objetivo é entender a estrutura da base.

## Exercício 1 — Tamanho da base

Execute o código abaixo e responda:

1. Quantas linhas existem na base?
2. Quantas colunas existem?
3. Cada linha representa o quê?

In [4]:
df.shape

(1000, 8)

**Resposta do aluno:**

A tabela possui 8 colunas e 1000 linhas. Cada linha representa o conjunto de dados de um aluno.

## Exercício 2 — Tipos das variáveis

Execute o código abaixo e responda:

1. Quais colunas são numéricas?
2. Quais colunas são categóricas/texto?
3. Por que isso é importante antes de fazer gráficos ou cálculos?

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   genero              1000 non-null   object
 1   grupo_etnico        1000 non-null   object
 2   escolaridade_pais   1000 non-null   object
 3   tipo_almoco         1000 non-null   object
 4   curso_preparatorio  1000 non-null   object
 5   nota_matematica     1000 non-null   int64
 6   nota_leitura        1000 non-null   int64
 7   nota_escrita        1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

**Resposta do aluno:**

As colunas numéricas são `nota_matematica`, `nota_leitura` e `nota_escrita`. As demais colunas são categóricas.
É importante identificar os tipos de dados para saber que colunas contém valores numéricos para cálculos e uso em gráficos.

## Exercício 3 — Primeira leitura dos dados

Observe as primeiras linhas da base e responda:

1. As colunas parecem fáceis de entender?
2. O que as notas representam?
3. Que perguntas de negócio ou de análise poderiam ser feitas com essa base?

In [6]:
df.head(10)

,genero,grupo_etnico,escolaridade_pais,tipo_almoco,curso_preparatorio,nota_matematica,nota_leitura,nota_escrita
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

**Resposta do aluno:**

Escreva aqui sua interpretação.

## Exercício 4 — Valores ausentes e duplicados

Execute os códigos e responda:

1. Existem valores ausentes?
2. Existem linhas duplicadas?
3. Se existissem valores ausentes em notas, seria correto preencher automaticamente com a média? Justifique.

In [7]:
df.isnull().sum()

genero                0
grupo_etnico          0
escolaridade_pais     0
tipo_almoco           0
curso_preparatorio    0
nota_matematica       0
nota_leitura          0
nota_escrita          0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

**Resposta do aluno:**

A tabela não possui valores ausentes nem linhas duplicadas.
No caso de valores ausentes em notas não faz sentido preencher automaticamente com a média porque isso alteraria os resultados dos alunos.

# Nível médio — estatística descritiva e interpretação

Agora vamos analisar média, mediana, desvio padrão, quartis e diferenças entre grupos.

## Exercício 5 — Estatísticas gerais das notas

Execute o código e responda:

1. Qual nota tem maior média?
2. Qual nota tem menor média?
3. A média e a mediana estão próximas? O que isso sugere?
4. Alguma disciplina parece ter maior dispersão?

In [ ]:
df[['nota_matematica', 'nota_leitura', 'nota_escrita']].describe()

**Resposta do aluno:**

Escreva aqui sua interpretação.

## Exercício 6 — Média x mediana

Execute o código e responda:

1. Em qual nota a média e a mediana são mais diferentes?
2. O que uma diferença grande entre média e mediana poderia indicar?
3. Neste caso, você usaria média ou mediana para representar melhor o desempenho geral? Justifique.

In [ ]:
resumo_notas = pd.DataFrame({
    'media': df[['nota_matematica', 'nota_leitura', 'nota_escrita']].mean(),
    'mediana': df[['nota_matematica', 'nota_leitura', 'nota_escrita']].median(),
    'desvio_padrao': df[['nota_matematica', 'nota_leitura', 'nota_escrita']].std()
})

resumo_notas

**Resposta do aluno:**

Escreva aqui sua interpretação.

## Exercício 7 — Quartis e IQR

Execute o código e responda:

1. O que representa o Q1?
2. O que representa o Q3?
3. O que o IQR mostra sobre as notas?
4. Em qual disciplina os 50% centrais parecem mais espalhados?

In [ ]:
quartis = df[['nota_matematica', 'nota_leitura', 'nota_escrita']].quantile([0.25, 0.5, 0.75])
quartis

In [ ]:
iqr = df[['nota_matematica', 'nota_leitura', 'nota_escrita']].quantile(0.75) - df[['nota_matematica', 'nota_leitura', 'nota_escrita']].quantile(0.25)
iqr

**Resposta do aluno:**

Escreva aqui sua interpretação.

## Exercício 8 — Comparando grupos: curso preparatório

Execute o código e responda:

1. Quem fez curso preparatório teve médias maiores?
2. A diferença parece pequena ou relevante?
3. Podemos afirmar que o curso preparatório causou notas maiores? Por quê?

In [ ]:
df.groupby('curso_preparatorio')[['nota_matematica', 'nota_leitura', 'nota_escrita']].mean().round(2)

**Resposta do aluno:**

Escreva aqui sua interpretação.

## Exercício 9 — Comparando grupos: tipo de almoço

Execute o código e responda:

1. Existe diferença entre estudantes com almoço padrão e almoço reduzido/gratuito?
2. Em quais notas a diferença aparece mais?
3. Que hipótese essa comparação pode gerar?

In [ ]:
df.groupby('tipo_almoco')[['nota_matematica', 'nota_leitura', 'nota_escrita']].mean().round(2)

**Resposta do aluno:**

Escreva aqui sua interpretação.

# Nível difícil — visualização, outliers e relatório interpretativo

Nesta parte, o aluno precisa interpretar padrões, anomalias e possíveis decisões de análise.

## Exercício 10 — Histograma das notas

Execute os histogramas e responda:

1. As notas parecem simétricas ou assimétricas?
2. Existe concentração em alguma faixa de nota?
3. Há indícios de notas muito baixas ou muito altas?
4. A média parece representar bem essas distribuições?

In [ ]:
for coluna in ['nota_matematica', 'nota_leitura', 'nota_escrita']:
    plt.figure(figsize=(8, 4))
    plt.hist(df[coluna], bins=20, edgecolor='black')
    plt.title(f'Histograma - {coluna}')
    plt.xlabel('Nota')
    plt.ylabel('Quantidade de estudantes')
    plt.show()

**Resposta do aluno:**

Escreva aqui sua interpretação.

## Exercício 11 — Boxplot e possíveis outliers

Execute os boxplots e responda:

1. Existem pontos muito abaixo do padrão?
2. Esses pontos devem ser removidos automaticamente?
3. Que tipo de investigação deveria ser feita antes de remover algum valor?

In [ ]:
for coluna in ['nota_matematica', 'nota_leitura', 'nota_escrita']:
    plt.figure(figsize=(6, 4))
    plt.boxplot(df[coluna], vert=False)
    plt.title(f'Boxplot - {coluna}')
    plt.xlabel('Nota')
    plt.show()

**Resposta do aluno:**

Escreva aqui sua interpretação.

## Exercício 12 — Identificando outliers pelo IQR

Execute o código e responda:

1. Quais valores são considerados possíveis outliers?
2. Eles parecem erro de digitação ou casos reais?
3. Por que uma nota baixa pode ser importante para a análise?

In [ ]:
coluna = 'nota_matematica'

q1 = df[coluna].quantile(0.25)
q3 = df[coluna].quantile(0.75)
iqr = q3 - q1

limite_inferior = q1 - 1.5 * iqr
limite_superior = q3 + 1.5 * iqr

print('Q1:', q1)
print('Q3:', q3)
print('IQR:', iqr)
print('Limite inferior:', limite_inferior)
print('Limite superior:', limite_superior)

outliers_matematica = df[(df[coluna] < limite_inferior) | (df[coluna] > limite_superior)]
outliers_matematica[[coluna, 'genero', 'tipo_almoco', 'curso_preparatorio', 'escolaridade_pais']]

**Resposta do aluno:**

Escreva aqui sua interpretação.

## Exercício 13 — Gráfico comparativo por curso preparatório

Execute o gráfico e responda:

1. O curso preparatório parece estar associado a notas maiores?
2. A diferença é parecida em matemática, leitura e escrita?
3. Que cuidado devemos ter ao interpretar esse resultado?

In [ ]:
medias_curso = df.groupby('curso_preparatorio')[['nota_matematica', 'nota_leitura', 'nota_escrita']].mean()

medias_curso.plot(kind='bar', figsize=(8, 5))
plt.title('Média das notas por curso preparatório')
plt.xlabel('Curso preparatório')
plt.ylabel('Média da nota')
plt.xticks(rotation=0)
plt.show()

**Resposta do aluno:**

Escreva aqui sua interpretação.

### AULA 2

## Exercício 14 — Relatório automatizado com ydata-profiling

Este trecho é opcional. Se a biblioteca não estiver instalada, execute:

`pip install ydata-profiling`

Depois rode o código abaixo.

Responda:

1. O relatório ajuda a encontrar padrões mais rápido?
2. Quais alertas ou informações chamaram atenção?
3. O relatório substitui a interpretação do analista? Justifique.

In [ ]:
# Caso necessário, instale antes:
# !pip install ydata-profiling

from ydata_profiling import ProfileReport

profile = ProfileReport(
    df,
    title='Relatório AED - Desempenho de Estudantes',
    explorative=True
)

profile.to_file('relatorio_aed_estudantes.html')

**Resposta do aluno:**

Escreva aqui sua interpretação.

### AULA 3

## Exercício 15 — Relatório automatizado com Sweetviz

Este trecho é opcional. Se a biblioteca não estiver instalada, execute:

`pip install sweetviz`

Depois rode o código abaixo.

Responda:

1. O Sweetviz facilita a comparação entre variáveis?
2. Que variável parece mais interessante para investigar?
3. Que risco existe em aceitar automaticamente tudo que o relatório mostra?

In [ ]:
# Caso necessário, instale antes:
# !pip install sweetviz

import sweetviz as sv

report = sv.analyze(df)
report.show_html('relatorio_sweetviz_estudantes.html')

**Resposta do aluno:**

Escreva aqui sua interpretação.

# Desafio final — mini relatório de AED

Com base em tudo que você analisou, escreva um mini relatório com:

1. O que a base representa.
2. Quais variáveis foram analisadas.
3. Quais padrões apareceram.
4. Se existem possíveis outliers.
5. Se há diferenças entre grupos.
6. Quais cuidados você teria antes de tomar decisões.
7. Uma hipótese que poderia ser investigada em uma próxima análise.

**Resposta do aluno:**

Escreva aqui seu mini relatório.